{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digital-twin-fraud.fullname" . }}-secret
  labels:
    {{- include "digital-twin-fraud.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  APP_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- if .Values.secrets.kafkaSaslUsername }}
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: {{ printf "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"%s\" password=\"%s\";" .Values.secrets.kafkaSaslUsername .Values.secrets.kafkaSaslPassword | quote }}
  {{- end }}
{{- end }}
